name: Process Data from Private Repo

# Trigger this workflow manually or through a dispatch event
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  

jobs:
  process-and-sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the public repository (it will serve as the execution context)
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      # Step 2: Clone the private repository into a separate folder
      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PRIVATE_REPO_URL}}.git private_repo
        env:
          PUBLIC_PAT: https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PRIVATE_REPO_URL}}.git

      - name: Set up environment and run script with secrets
        run: |
            echo "Setting up environment variables"
        env:
            API_KEY: ${{ secrets.API_KEY }}
            API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}

      - name: Add products
        run: node node /home/runner/work/supplier2_women_clothing_public/supplier2_women_clothing_public/add_products_new.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            LOCATION: ${{ secrets.LOCATION }}
            ADD_PRODUCTS: 'private_repo/clean_data/to_add.csv'

  keepalive-job:
        name: Keepalive Workflow
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - uses: actions/checkout@v4
        - uses: gautamkrishnar/keepalive-workflow@v2
