name: Process Data from Private Repo

# Trigger this workflow manually or through a dispatch event
on:
  workflow_dispatch:
  repository_dispatch:
    types: [process_data]

jobs:
  process-and-sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the public repository (it will serve as the execution context)
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      # Step 2: Clone the private repository into a separate folder
      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PRIVATE_REPO_URL}}.git private_repo
        env:
          PUBLIC_PAT: https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PRIVATE_REPO_URL}}.git

      - name: Set up environment and run script with secrets
        run: |
            echo "Setting up environment variables"
        env:
            API_KEY: ${{ secrets.API_KEY }}
            API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}

      - name: List All Files in Workspace
        run: find ${{ github.workspace }} -type f

      # Step 3: Run the data preprocessing script in the cloned private repo
      - name: Install Node.js dependencies 
        run: npm install axios csv-parser dotenv shopify-api-node fs
      
      - name: Iterate over the products
        run: node /home/runner/work/supplier2_women_clothing_public/supplier2_women_clothing_public/iterate_and_find.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            ITERATE_AND_FIND: 'private_repo/clean_data/new_clothes_cleaned.csv'
            FOLDER: 'private_repo/clean_data/'
      
      - name: Install Python dependencies
        run: pip install pandas requests lxml
      
      - name: Preprocess data
        run: python /home/runner/work/supplier2_women_clothing_public/supplier2_women_clothing_public/preprocess.py --input_folder "private_repo/clean_data/" --clean_file "new_clothes_cleaned.csv"
      
      - name: Update products
        run: node /home/runner/work/supplier2_women_clothing_public/supplier2_women_clothing_public/update_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}

      - name: Set inventory 0
        run: node /home/runner/work/supplier2_women_clothing_public/supplier2_women_clothing_public/set_zero_inventory.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
    
      - name: Update costs
        run: node /home/runner/work/supplier2_women_clothing_public/supplier2_women_clothing_public/update_costs.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}

      - name: Add products
        run: node node /home/runner/work/supplier2_women_clothing_public/supplier2_women_clothing_public/add_products_new.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
            LOCATION: ${{ secrets.LOCATION }}

      # Step 4: Push the cleaned data back to the private repo
      - name: Push Cleaned Data Back to Private Repository
        run: |
          cd private_repo
          git pull origin master --no-edit
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Processed data from public repo" || echo "No changes to commit"
          git push
        env:
          PRIVATE_REPO_PAT: ${{ secrets.PUBLIC_PAT }}https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PROFILE_URL }}/supplier2_women_clothing_private.git

  keepalive-job:
        name: Keepalive Workflow
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
        - uses: actions/checkout@v4
        - uses: gautamkrishnar/keepalive-workflow@v2
